config/routes.rb
BabyLog::Application.routes.draw do
  resources :feedings

end

app/models/feeding.rb
class Feeding < ActiveRecord::Base
  attr_accessible :endtime, :side, :starttime
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feedings_controller.rb
class FeedingsController < ApplicationController
  # GET /feedings
  # GET /feedings.json
  def index
    @feedings = Feeding.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedings }
    end
  end

  # GET /feedings/1
  # GET /feedings/1.json
  def show
    @feeding = Feeding.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feeding }
    end
  end

  # GET /feedings/new
  # GET /feedings/new.json
  def new
    @feeding = Feeding.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feeding }
    end
  end

  # GET /feedings/1/edit
  def edit
    @feeding = Feeding.find(params[:id])
  end

  # POST /feedings
  # POST /feedings.json
  def create
    @feeding = Feeding.new(params[:feeding])

    respond_to do |format|
      if @feeding.save
        format.html { redirect_to @feeding, notice: 'Feeding was successfully created.' }
        format.json { render json: @feeding, status: :created, location: @feeding }
      else
        format.html { render action: "new" }
        format.json { render json: @feeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedings/1
  # PUT /feedings/1.json
  def update
    @feeding = Feeding.find(params[:id])

    respond_to do |format|
      if @feeding.update_attributes(params[:feeding])
        format.html { redirect_to @feeding, notice: 'Feeding was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedings/1
  # DELETE /feedings/1.json
  def destroy
    @feeding = Feeding.find(params[:id])
    @feeding.destroy

    respond_to do |format|
      format.html { redirect_to feedings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedings_helper.rb
module FeedingsHelper
end

app/views/feedings/_form.html.erb
<%= form_for(@feeding) do |f| %>
  <% if @feeding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feeding.errors.count, "error") %> prohibited this feeding from being saved:</h2>

      <ul>
      <% @feeding.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :side %><br />
    <%= f.text_field :side %>
  </div>
  <div class="field">
    <%= f.label :starttime %><br />
    <%= f.datetime_select :starttime %>
  </div>
  <div class="field">
    <%= f.label :endtime %><br />
    <%= f.datetime_select :endtime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedings/edit.html.erb
<h1>Editing feeding</h1>

<%= render 'form' %>

<%= link_to 'Show', @feeding %> |
<%= link_to 'Back', feedings_path %>

app/views/feedings/index.html.erb
<h1>Listing feedings</h1>

<table>
  <tr>
    <th>Side</th>
    <th>Starttime</th>
    <th>Endtime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedings.each do |feeding| %>
  <tr>
    <td><%= feeding.side %></td>
    <td><%= feeding.starttime %></td>
    <td><%= feeding.endtime %></td>
    <td><%= link_to 'Show', feeding %></td>
    <td><%= link_to 'Edit', edit_feeding_path(feeding) %></td>
    <td><%= link_to 'Destroy', feeding, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feeding', new_feeding_path %>

app/views/feedings/new.html.erb
<h1>New feeding</h1>

<%= render 'form' %>

<%= link_to 'Back', feedings_path %>

app/views/feedings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Side:</b>
  <%= @feeding.side %>
</p>

<p>
  <b>Starttime:</b>
  <%= @feeding.starttime %>
</p>

<p>
  <b>Endtime:</b>
  <%= @feeding.endtime %>
</p>


<%= link_to 'Edit', edit_feeding_path(@feeding) %> |
<%= link_to 'Back', feedings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BabyLog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>